BEGIN;

DROP TABLE IF EXISTS USERS, POSTS, COMMENTS CASCADE;

CREATE TABLE users(
     id SERIAL PRIMARY KEY,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "username" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL
);

CREATE TABLE posts(
    id SERIAL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "image" VARCHAR(255),
    "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "user_id" INT NOT NULL,
    CONSTRAINT user_id FOREIGN KEY(user_id) REFERENCES USERS(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE comments(
    id SERIAL PRIMARY KEY,
    "content" TEXT NOT NULL,
    "post_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
 CONSTRAINT user_id FOREIGN KEY(user_id) REFERENCES USERS(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT post_id FOREIGN KEY(post_id) REFERENCES POSTS(id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMIT;


